name = "astral3deditor"
compatibility_date = "2025-05-06"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "pnpm build"

[build.environment]
NODE_VERSION = "18"

[assets]
  directory = "./dist"
